### ISSUE TITLE
Step 4 path should be `assets/scripts/books/ui.js`

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/jquery-ajax-get-collection#12] opened 2017-01-19 20:20 UTC
in ### Code Along: AJAX book Collection section

```md
1.  Add a collection success and fail handler to `assets/scripts/ui.js`.
```

**Comment by raq929** [comment] 2017-03-27 20:40
I suspect this is a duplicate of #3

**Closed as completed** 2017-03-30 15:35 UTC
